// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzbkcnuzybdscnoxxrqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6YmtjbnV6eWJkc2Nub3h4cnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjc0MzgsImV4cCI6MjA2MDY0MzQzOH0.Vd9djdJ69QnTtE6zhZ93jy4nz5PQIA9p7amyUvlIY7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);